In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = {"id":pd.Series(["2017010807","2017010870"],index=["wsp","ztj"]),
        "gender":pd.Series(["male","female"],index=["wsp","ztj"])}

In [4]:
data = pd.DataFrame(data)
print(data)

             id  gender
wsp  2017010807    male
ztj  2017010870  female


In [5]:
print(data.loc["wsp"])

id        2017010807
gender          male
Name: wsp, dtype: object


In [6]:
print(data["id"])

wsp    2017010807
ztj    2017010870
Name: id, dtype: object


In [7]:
print(data.iloc[0])

id        2017010807
gender          male
Name: wsp, dtype: object


In [11]:
print(data[0:1])

             id gender
wsp  2017010807   male


In [10]:
print(data[[True,False]])

             id gender
wsp  2017010807   male


In [22]:
def MSE(a,s=None):
    return np.sum((a-s)**2)/a.size if s is not None else np.sum((a-np.mean(a))**2)/a.size

a = np.array([72, 94, 79, 83, 65, 81, 73, 67, 85, 82])
print(MSE(a,a-2))

4.0


In [24]:
def CE(a, b):
    return -np.sum(a*np.log(b))


print(CE(np.array([1, 0]), np.array([0.9, 0.1])))
print(CE(np.array([1, 0]), np.array([0.1, 0.9])))
print(CE(np.array([0, 1]), np.array([0.2, 0.8])))

0.10536051565782628
2.3025850929940455
0.2231435513142097


In [29]:
a = np.random.randn(4,4)
b = np.random.randn(4,5,6)
print(a)
print(b)

[[-0.6882084   1.09473185 -0.64667119  0.14414629]
 [-1.50128383  0.10262278 -2.99018585  0.54002846]
 [-0.4902759  -0.7573055   0.28189489 -0.8092373 ]
 [-0.14768079 -0.66521363 -0.72395254 -1.92935531]]
[[[ 0.06204503  0.13707508  0.0711302  -2.1620055   1.16476794
   -2.61672696]
  [ 1.36705096 -1.21703924  2.25719229 -1.09460105  1.3838433
   -0.92351856]
  [ 0.54670037 -0.42026684  0.88753098 -1.33468541  0.13488257
   -0.24934627]
  [ 2.49895494  1.31859937 -0.00502772  0.18138806  0.18244312
   -1.78206331]
  [-1.02788424 -0.77072343  0.033165    0.31294723  1.75179864
   -1.31348255]]

 [[ 0.66725168 -0.33120692 -0.32185518 -1.25405324 -0.55202494
   -0.73949044]
  [-0.71105467 -0.3238888  -0.91300155  0.22926458  0.61439242
   -1.91334392]
  [-0.6064469  -0.5765003  -0.20725783  0.86469126  1.41725917
    1.37843864]
  [-0.0655154   0.62912409  0.31060016  0.3563538   2.01266758
   -0.86020928]
  [-0.01666742 -1.35717523 -0.01058115  0.49591085  1.16541409
   -1.0511401 ]]

 [